In [1]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
modelLM = SentenceTransformer("all-MiniLM-L6-v2")

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
modelUSE = hub.load(module_url)

In [25]:
from qtn_sim import *


circuit1 = QCircuit()
circuit1.addGate(HGate(), [0])
circuit1.addGate(CNOTGate(), [0,1])
circuit1.addGate(XGate(), [1])

circuit2 = QCircuit()
circuit2.addGate(HGate(), [0])

circuit3 = QCircuit()
circuit3.addGate(CNOTGate(), [0,1])
circuit3.addGate(XGate(), [1])

circuit4 = QCircuit()
circuit4.addGate(TOFFOLIGate(), [0,1,2])

circuits = [circuit1, circuit2, circuit3, circuit4]

In [26]:
c = [modelUSE([circ.toString()]).numpy()[0] for circ in circuits]

from sklearn.metrics.pairwise import pairwise_distances

print("Pairwise dist")
print(pairwise_distances(c, metric='sqeuclidean'))


from sklearn.decomposition import PCA
pca = PCA(n_components=3)
x = pca.fit_transform(c)

print("PCA 3 components")
print(x)

print("First circuit")
print(x[0])
print("Sum of both c1 and c2")
print(x[1]+ x[2])

print("Dist from first circuit to sum of 2nd and 3rd ")
print(np.linalg.norm(x[0] - (x[1]+x[2])))
print(np.linalg.norm(x[0] - x[3]))

x = c

Pairwise dist
[[0.         0.70889982 0.85483866 1.30441326]
 [0.70889982 0.         1.8566337  1.95847407]
 [0.85483866 1.8566337  0.         1.06119021]
 [1.30441326 1.95847407 1.06119021 0.        ]]
PCA 3 components
[[-0.25565307 -0.19607227  0.35945376]
 [-0.75750262  0.17794213 -0.20371592]
 [ 0.4307547  -0.4886776  -0.18649968]
 [ 0.58240099  0.50680773  0.03076184]]
First circuit
[-0.25565307 -0.19607227  0.35945376]
Sum of both c1 and c2
[-0.32674792 -0.31073547 -0.3902156 ]
Dist from first circuit to sum of 2nd and 3rd 
0.7617127244924297
1.1421091284035807


In [ ]:
# print(x)

print(x[0][:2])
print(x[1][:2] + x[2][:2])

print(np.linalg.norm(x[0].numpy() - (x[1].numpy()+x[2].numpy())))
print(np.linalg.norm(x[0].numpy() - x[3].numpy()))


tf.Tensor([ 0.01090853 -0.06033376], shape=(2,), dtype=float32)
tf.Tensor([-0.03178316 -0.11530195], shape=(2,), dtype=float32)
1.0812609
1.3575324
